---
pve_lxcs_seerr01:
  seerr01:
    vmid: 115
    hostname: seerr01.aah.muffn.io
    node: pve03
    cores: 2
    memory: 2048
    swap: 512
    disk: "16G"
    network_ip: "10.82.10.115/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - os_linux
      - os_trixie
      - site_aah
      - podman_app
      - app_seerr
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
