---
# LCY site variables

site_code: lcy
pve_system_domain: lcy.muffn.io
pve_system_nameservers:
  - 10.83.7.102
pve_system_search_domains: 
  - lcy.muffn.io
  - aah.muffn.io
  - lgy.muffn.io
  - internal.muffn.io # Legacy - needs to be migrated from
pve_system_ntp_enabled: true
pve_system_ntp_servers: 
  - 10.83.2.1
