---
pve_lxcs_sabnzbd01:
  sabnzbd01:
    vmid: 113
    hostname: sabnzbd01.aah.muffn.io
    node: pve03
    cores: 12
    memory: 8192
    swap: 512
    disk: "64G"
    storage: "local-zfs"
    network_ip: "10.82.10.113/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - os_linux
      - os_trixie
      - site_aah
      - podman_app
      - app_sabnzbd
    features: "{{ lxc_features_podman }}"
    bind_mounts:
      - host_path: /mnt/scratch/downloads
        lxc_path: /mnt/downloads
        shared: true
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
