---
pve_lxcs_rembg01:
  rembg01:
    vmid: 131
    hostname: rembg01.aah.muffn.io
    node: pve03
    cores: 4
    memory: 2048
    swap: 2048
    disk: "16G"
    network_ip: "10.82.10.131/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - os_linux
      - os_trixie
      - site_aah
      - podman_app
      - app_rembg
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
