---
- name: Fail if root SSH keys are empty
  ansible.builtin.fail:
    msg: "No SSH keys were configured for Proxmox root user."
  when: pve_root_authorized_keys | default('', true) | trim == ''

- name: Ensure .ssh directory exists for root
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Set authorized_keys for root
  ansible.posix.authorized_key:
    user: root
    key: "{{ pve_root_authorized_keys }}"
    exclusive: "{{ pve_root_authorized_keys_exclusive }}"
