---
pve_lxcs_infisical01:
  infisical01:
    vmid: 131
    hostname: infisical01.lcy.muffn.io
    cores: 2
    memory: 4096
    swap: 512
    disk: "20G"
    network_ip: "10.83.7.131/24"
    network_gw: "10.83.7.1"
    network_vlan: 7
    unprivileged: true
    tags:
      - ansible
      - os_linux
      - os_trixie
      - site_lcy
      - podman_app
      - app_infisical
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
