---
- name: Deploy wgtun and ancillary apps
  hosts: "{{ target | default('wgtun01.aah.muffn.io') }}"
  become: true
  gather_facts: true

  roles:
    - role: lxc/base
      tags: [base, setup]
    - role: podman
      tags: [podman, install]
    - role: apps/wgtun
      tags: [wgtun, config, auth]
    - role: apps/podman_app
      tags: [app, deploy]
