---
- name: Deploy GitHub Actions runner
  hosts: "{{ target | default('tag_app_github_runner') }}"
  become: true
  gather_facts: true
  roles:
    - role: linux/base
      tags: [base, setup]
    - apps/github_runner
