---
podman_enabled: true

podman_apps:
  plex:
    enabled: true
    image: plexinc/pms-docker
    tag: plexpass
    port: 32400
    uid: 1000
    gid: 1000
    network_mode: host
    tmpfs:
      - /transcode
    volumes:
      - /opt/plex/config:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
      - /mnt/media/music:/music
      - /mnt/media/youtube:/youtube
    devices:
      - /dev/dri/renderD128
      - /dev/dri/card0
    env:
      TZ: Europe/London
      PLEX_UID: "1000"
      PLEX_GID: "1000"
      CHANGE_CONFIG_DIR_OWNERSHIP: "true"
      # PLEX_CLAIM_TOKEN: claim-xxxxxx
