---
pve_lxcs_appmisc:
  shelfmark01:
    vmid: 121
    hostname: shelfmark01.aah.muffn.io
    node: pve03
    cores: 2
    memory: 2048
    swap: 512
    disk: "16G"
    network_ip: "10.82.10.121/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - podman_app
      - app_shelfmark
    features: "{{ lxc_features_podman }}"
    bind_mounts:
      - host_path: /mnt/scratch/bookdrop
        lxc_path: /books
        shared: true
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
  beszel01:
    vmid: 122
    hostname: beszel01.aah.muffn.io
    node: pve03
    cores: 1
    memory: 1024
    swap: 512
    disk: "16G"
    network_ip: "10.82.10.122/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - podman_app
      - app_beszel
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
  grimmory01:
    vmid: 123
    hostname: grimmory01.aah.muffn.io
    node: pve03
    cores: 2
    memory: 4096
    swap: 512
    disk: "32G"
    network_ip: "10.82.10.123/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - podman_app
      - app_grimmory
    features: "{{ lxc_features_podman }}"
    bind_mounts:
      - host_path: /mnt/scratch/bookdrop
        lxc_path: /bookdrop
        shared: true
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
  pulse01:
    vmid: 105
    hostname: pulse01.aah.muffn.io
    node: pve04
    cores: 2
    memory: 2048
    swap: 512
    disk: "32G"
    network_ip: "10.82.10.105/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - podman_app
      - app_pulse
    features:
      nesting: true
      keyctl: false
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
  zipline01:
    vmid: 119
    hostname: zipline01.aah.muffn.io
    node: pve03
    cores: 2
    memory: 4096
    swap: 512
    disk: "32G"
    network_ip: "10.82.10.119/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - podman_app
      - app_zipline
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
  paperless01:
    vmid: 124
    hostname: paperless01.aah.muffn.io
    node: pve03
    cores: 2
    memory: 4096
    swap: 512
    disk: "32G"
    network_ip: "10.82.10.124/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - podman_app
      - app_paperless
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
  changedetection01:
    vmid: 128
    hostname: changedetection01.aah.muffn.io
    node: pve03
    cores: 4
    memory: 4096
    swap: 512
    disk: "16G"
    network_ip: "10.82.10.128/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - podman_app
      - app_changedetection
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"