---
podman_enabled: true

seafile_nfs_server: "10.82.7.122"
seafile_nfs_path: "/mnt/pool-01/containers/seafile"
seafile_nfs_opts: "rw,nolock,soft,nfsvers=4"
seafile_nfs_volume_name: "seafile-data"

podman_networks:
  seafile:
    driver: bridge

podman_volumes:
  "{{ seafile_nfs_volume_name }}":
    driver: local
    options:
      - "type=nfs"
      - "o={{ seafile_nfs_opts }}"
      - "device={{ seafile_nfs_server }}:{{ seafile_nfs_path }}"

podman_apps:
  mariadb:
    enabled: true
    image: mariadb
    # renovate: datasource=docker depName=mariadb versioning=docker allowedVersions=/^10\.11\.\d+$/
    tag: "10.11"
    network: seafile
    volumes:
      - /opt/seafile/db:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{ seafile_db_root_password | trim }}"
      MYSQL_LOG_CONSOLE: "true"
      MARIADB_AUTO_UPGRADE: "1"
    restart: always

  memcached:
    enabled: true
    image: memcached
    # renovate: datasource=docker depName=memcached versioning=docker allowedVersions=/^1\.6\.\d+$/
    tag: "1.6"
    network: seafile
    restart: always

  seafile:
    enabled: true
    image: seafileltd/seafile-pro-mc
    # renovate: datasource=docker depName=seafileltd/seafile-pro-mc
    tag: "12.0-latest"
    port: 8443
    container_port: 443
    network: seafile
    after:
      - mariadb.service
      - memcached.service
    requires:
      - mariadb.service
      - memcached.service
    security_label_disable: true
    volumes:
      - "{{ seafile_nfs_volume_name }}:/shared"
      - /opt/seafile/ssl:/shared/ssl:ro
      - /opt/seafile/nginx:/shared/nginx/conf
      - /opt/seafile/conf/seahub_settings.py:/shared/seafile/conf/seahub_settings.py
    files:
      - dest: /opt/seafile/ssl/{{ inventory_hostname }}.crt
        content: "{{ seafile_tls_cert }}"
        mode: '0644'
      - dest: /opt/seafile/ssl/{{ inventory_hostname }}.key
        content: "{{ seafile_tls_key }}"
        mode: '0600'
      - dest: /opt/seafile/nginx/seafile.nginx.conf
        template_src: seafile.nginx.conf.j2
        mode: '0644'
      - dest: /opt/seafile/conf/seahub_settings.py
        template_src: seahub_settings.py.j2
        mode: '0755'
    env:
      TZ: Europe/London
      TIME_ZONE: Europe/London
      SEAFILE_SERVER_HOSTNAME: "{{ inventory_hostname }}"
      DB_HOST: mariadb
      DB_ROOT_PASSWD: "{{ seafile_db_root_password | trim }}"
      SEAFILE_ADMIN_EMAIL: "{{ seafile_admin_email | trim }}"
      SEAFILE_ADMIN_PASSWORD: "{{ seafile_admin_password | trim }}"
      SEAFILE_SERVER_LETSENCRYPT: "false"
      FORCE_HTTPS_IN_CONF: "true"
      MEMCACHE_HOST: memcached
      MEMCACHE_PORT: "11211"
      JWT_PRIVATE_KEY: "{{ seafile_jwt_private_key | trim }}"
    restart: always
